# Research crew task configurations
verify_facts:
    description: >
        Verify all claims and search for current information. Required steps:
        1. Use search_tool to find latest information about the topic
        2. Find and verify primary sources from the last 24 hours
        3. Cross-reference with multiple reliable news sources
        4. Note any discrepancies or recent developments
        5. Provide confidence score and timestamp for each fact
        6. List all sources with their publication dates
    expected_output: Detailed fact-check report with recent sources and confidence scores
    agent: fact_checker
    required_tools: [search_tool]

research_context:
    description: >
        Research broader context around the topic:
        1. Find relevant background information
        2. Identify related trending discussions
        3. Look for recent developments
        4. Find relevant statistics and data
        5. Identify expert opinions and analysis
    expected_output: Comprehensive context report with background information
    agent: context_researcher
    context: [verify_facts]

enhance_content:
    description: >
        Using verified facts and contextual research:
        1. Suggest ways to enhance the content
        2. Provide relevant data points
        3. Identify potential angles for engagement
        4. Suggest credible sources to reference
        5. Format information for social media impact
    expected_output: Enhanced content suggestions with supporting data
    agent: content_enhancer
    context: [verify_facts, research_context]
