# Research crew task configurations
verify_facts:
    description: >
        Analyze and verify information using the search_data provided:
        1. Process all search results from search_data.results
        2. Extract key facts and claims from each result
        3. Cross-reference information across multiple sources
        4. Evaluate source credibility and information consistency
        5. Compile verified facts with confidence scores
        6. Organize findings by relevance and reliability
    expected_output: >
        {
          "topics": ["verified topics extracted from search results"],
          "facts": ["verified facts with supporting evidence"],
          "sources": [{"title": "source title", "url": "source url", "credibility": "score"}],
          "confidence_score": "aggregated verification score"
        }
    agent: fact_checker

research_context:
    description: >
        Research broader context around the topic:
        1. Find relevant background information
        2. Identify related trending discussions
        3. Look for recent developments
        4. Find relevant statistics and data
        5. Identify expert opinions and analysis
    expected_output: Comprehensive context report with background information
    agent: context_researcher
    context: [verify_facts]

enhance_content:
    description: >
        Using verified facts and contextual research:
        1. Suggest ways to enhance the content
        2. Provide relevant data points
        3. Identify potential angles for engagement
        4. Suggest credible sources to reference
        5. Format information for social media impact
    expected_output: Enhanced content suggestions with supporting data
    agent: content_enhancer
    context: [verify_facts, research_context]
