# Research crew task configurations
    verify_facts:
        description: >
            Verify all claims in the provided content using search tools.
            Find primary sources and cross-reference with reliable sources.
            Provide confidence scores and list all sources used.
        expected_output: Detailed fact-check report with sources and confidence scores
        agent: fact_checker

    research_context:
        description: >
            Research broader context around the topic including background information,
            trending discussions, and recent developments.
        expected_output: Comprehensive context report with background information
        agent: context_researcher
        context: [verify_facts]

    enhance_content:
        description: >
            Using verified facts and contextual research, enhance the content
            with relevant data points and engagement angles.
        expected_output: Enhanced content suggestions with supporting data
        agent: content_enhancer
        context: [verify_facts, research_context]
